name: conda-basic
channels:
    - r
dependencies:
    - python=2.7
    - numpy
    - scipy
    - cython
    - ipython
    - jupyter
    - pandas
    - matplotlib
    - scikit-learn
    - statsmodels
    - docopt
    - rpy2 # Use this version from the r channel so that it works
    - r-ggplot2
    - r-dplyr
    - pip:
        - "git+https://github.com/pygridtools/gridmap.git#egg=gridmap"
      # Can also install your own packages from a remote repo:
        #- "--editable=git+ssh://github.com/USERNAME/REPONAME.git@COMMIT#egg=REPONAME"
        # The --editable flag is important in order to get `pip freeze` to tell
        # you the COMMIT hash. Can also put branches and tags for COMMIT, but
        # for reproducibility best to use COMMIT hashes.
        - ipdb
